# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################


# Sometimes we create a record type with just one field, that is meant
# to be extend later. In such cases, this warning is non-helpful.
- ignore: {name: "Use newtype instead of data"}
