#!/usr/bin/env bash

test_case() {
    base="$1"
    test_file="${base}.cairo"
    printf "# checking %s\n" "$test_file" >&3
    gold_file="${base}.gold"
    compiled_file="${base}.json"
    temp_file="${base}.temp"

    horus-compile "$test_file" --cairo_path=./tests/resources/golden/ > "$compiled_file"
    stack run horus-check "$compiled_file" -- -s mathsat -s z3 -t 20000 &> "$temp_file" || true
    diff "$gold_file" "$temp_file" \
         --unified \
         --ignore-trailing-space \
         --ignore-blank-lines \
         --new-file # treat absent files as empty
    rm "$compiled_file"
    rm "$temp_file"
    rm "$base.out" -rf
}
